### PR TITLE
Fixed Broken iOS Touch Controls on Re-mounting

### LINKED ISSUE #115: Broken direction control
The following issue appears on:

OS: iOS 12.3.1
iPhone SE
Browsers: Safari (incl. PWA), Firefox (17.3), Chrome (75.0.3770.103)
Roms: Pokémon Yellow, Zelda Links Awakening

After few minutes of playing the direction control is absolutely broken. Especially in full size mode.

### PR DESCRIPTION
**Pull request by torch2424**
closes #115 

cc @Kcorab

So this was actually due to a TODO I had in the source code I incorrectly referenced to an issue. 

But essentially, at the time our downstream dependancy [responsive gamepad did not support removing touch inputs](https://github.com/torch2424/responsive-gamepad/issues/26). And we needed this, as we re-render the touch pad on every "layout change". Thus, the touch inputs were "doubling up", therefore you would end up pressing multiple overlapping invisible inputs. This is probably due to the viewport zoom that iOS allows, mixed with the layou change to create a weird platform specific bug :thinking: 

But to prove this is the issue, from the JS Logs I saw:

IMG_0006

And after the fix, everything was working! (This is an image, but trust me it totally does haha)

IMG_0007

And you can see the files changes to see the todo I just quickly implemented :smile: :+1: 

P.S I updated the dependencies to solve a handful of `npm audit` issues :smile:

### CODE REVIEW

**Comment by Kcorab** [comment]
Could you deploy the current master so it's available here: https://vaporboy.net/ :grin:

**Comment by torch2424** [comment]
Did I never deploy? :upside_down_face: 

Yeah I can do that now! :smile: Thanks for reminding me! :smile: @Kcorab

**Comment by torch2424** [comment]
This is now deployed! Thanks for the heads up! :smile: @Kcorab ! 

What happened was my server was acting up :upside_down_face: I think my auto deploy webhooks got borked or soemthing.

**Comment by Kcorab** [comment]
@torch2424

Thank you so much! Awesome job!
Im playing gbc games on an iPhone. A dream come true. =)

**Comment by torch2424** [comment]
You are welcome! :smile: @Kcorab ! Glad that you are stoked on the emulator :+1:

**Pull request merged**
